"""Added functions and more relations to review  model

Revision ID: 0ab1390c2c0e
Revises: 1fcecfda3f37
Create Date: 2023-09-05 14:33:33.248734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab1390c2c0e'
down_revision = '1fcecfda3f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
