"""Added  model

Revision ID: 1fcecfda3f37
Revises: c5b791406ad1
Create Date: 2023-09-05 14:13:29.103269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcecfda3f37'
down_revision = 'c5b791406ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
