"""modifyingmodel

Revision ID: 543558c114e6
Revises: f8826519ce8b
Create Date: 2023-09-05 14:39:57.184972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543558c114e6'
down_revision = 'f8826519ce8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
