"""Added to model

Revision ID: 5ae092c66b6c
Revises: 0ab1390c2c0e
Create Date: 2023-09-05 14:36:52.512105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae092c66b6c'
down_revision = '0ab1390c2c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
