"""Manipulated  model

Revision ID: c5b791406ad1
Revises: 0bb729df688f
Create Date: 2023-09-05 14:06:46.562522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b791406ad1'
down_revision = '0bb729df688f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('star_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('reviews', 'reviews')
    op.drop_column('reviews', 'star_ratings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('star_ratings', sa.INTEGER(), nullable=True))
    op.add_column('reviews', sa.Column('reviews', sa.VARCHAR(), nullable=True))
    op.drop_column('reviews', 'comment')
    op.drop_column('reviews', 'star_rating')
    # ### end Alembic commands ###
