"""modifying  model

Revision ID: f8826519ce8b
Revises: 5ae092c66b6c
Create Date: 2023-09-05 14:39:08.863963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8826519ce8b'
down_revision = '5ae092c66b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
